# https://docs.codecov.com/docs/codecovyml-reference
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  require_changes: false
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default

flags:
  unit:
    paths:
      - src/
