coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment: false

flags:
  unit:
    paths:
      - src/

ignore:
  - tests/**
  - __mocks__/**
  - jest/**

