name: 'Check Pull Request Incremental Changes'
description: |
  Detects actual file changes in PR opened or synchronize events, ignoring false positives from merge commits.
  
  This action is specifically designed for pull_request synchronize events where you need to distinguish 
  between actual changes pushed to the PR versus changes that came from merging the base branch.
  
  For simple file change detection in PRs, use `gh pr diff <pr_number>` instead.

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token for API access'
    required: true
  FILE_PATHS:
    description: 'JSON array of file paths to check (e.g., ["src/languages/en.ts", "package.json"]). If not provided, all files in the PR will be checked.'
    required: false
outputs:
  CHANGED_FILES:
    description: 'JSON array of file paths that were actually changed in the PR (not from merged commits)'
runs:
  using: 'node20'
  main: './index.js'
