name: Changed files ESLint check

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]
    paths: ['**.js', '**.ts', '**.tsx', '**.json', '**.mjs', '**.cjs', 'config/.editorconfig', '.watchmanconfig', '.imgbotconfig']

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('{0}-{1}', github.ref, github.sha) || github.ref }}-changed-lint
  cancel-in-progress: true

jobs:
  lint-changed:
    name: Changed files ESLint check
    if: ${{ github.actor != 'OSBotify' || github.event_name == 'workflow_call' }}
    runs-on: ubuntu-latest
    steps:
      - name: Count commits between merge base and HEAD
        id: count
        run: |
          # Fetch the number of commits from base up to and including main.
          RAW_COUNT="$(gh api "repos/$REPO/compare/${BASE}...main" | jq -r '.total_commits')"
          # When fetching we need to fetch the history + base + temp merge commit, thus +2.
          ADJUSTED_COUNT=$((RAW_COUNT + 2))
          echo "count=$ADJUSTED_COUNT" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}
          BASE: ${{ github.event.pull_request.base.sha }}
          REPO: ${{ github.repository }}
          
      - name: Checkout
        # v4
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          fetch-depth: ${{ fromJSON(steps.count.outputs.count) }}

      - name: Setup Node
        uses: ./.github/actions/composite/setupNode
        with:
          IS_DESKTOP_BUILD: true
 
      - name: Run ESLint to check for deprecation warnings
        run: |
          # shellcheck disable=SC2046
          npm run lint-changed
