name: React Compiler Compliance Check

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]
    paths: ['**.js', '**.ts', '**.tsx', '**.mjs', '**.cjs', 'package.json', 'react-compiler-config.json']

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('{0}-{1}', github.ref, github.sha) || github.ref }}-react-compiler-compliance
  cancel-in-progress: true
jobs:
  react-compiler-compliance:
    name: React Compiler Compliance
    if: ${{ github.actor != 'OSBotify' || github.event_name == 'workflow_call' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for git diff

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.4'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run React Compiler Compliance Check
        run: npm run react-compiler-compliance-check check-changed
