name: Remote Build iOS

on:
  workflow_dispatch:
  push:
    branches-ignore: [staging, production]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: macos-15-xlarge
    strategy:
      matrix:
        include:
          - destination: simulator
            project_root: ./
            scheme: 'New Expensify Dev'
            configuration: 'DebugDevelopment'

          - destination: simulator
            project_root: Mobile-Expensify/
            scheme: 'Expensify Dev'
            configuration: 'Debug'
            is_hybrid_build: true
    steps:
      - name: Checkout
        # v4
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          submodules: ${{ matrix.is_hybrid_build == 'true' || false }}
          token: ${{ matrix.is_hybrid_build == 'true' && secrets.OS_BOTIFY_TOKEN || github.token }}

      - name: Setup Node
        uses: ./.github/actions/composite/setupNode

      - name: RNEF Remote Build - iOS
        uses: callstackincubator/ios@4c2dcc0d6b9c35407cf294e17386b65258a3b6af
        env:
          PROJECT_ROOT_PATH: ${{ matrix.project_root }}
        with:
          destination: ${{ matrix.destination }}
          scheme: ${{ matrix.scheme }}
          configuration: ${{ matrix.configuration }}
          github-token: ${{ github.token }}
          comment-bot: false
